global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost':9100']
    scrape_interval: 5s
    basic_auth:
      username: prom
      password: prom

remote_write:
  - url: 'http://localhost:9090'
    basic_auth:
      username: 'admin'
      password: 'admin'